# from: https://github.com/PoliNetworkOrg/TheTOLProject/blob/main/.github/workflows/labels-sync.yml

name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - ".github/labels.yml"
  workflow_dispatch:

jobs:
  sync:
    name: Run EndBug/label-sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label-sync@v2
        with:
          config-file: ".github/labels.yml"
